name: BMI

on:
  push: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      # Checkout and install prerequisites
      - name: Use Nodejs
        uses: actions/checkout@v3
        with:
          node-version: '16'
      - name: Artifactory 
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_EXPORT: ${{ secrets.JF_EXPORT }}
      # Buildd
      - run: npm i
      - run: ls && pwd
      - run: tar -cvf $GITHUB_WORKFLOW.tar.gz *
      - run: ls && pwd
      #Upload Artifactss
      - run: jfrog --version
      - run: jfrog config show
      - run: jfrog rt upload --url=${{ secrets.JF_URL }} --user=admin --password=${{ secrets.JF_PASS }} "package.json" BMI/
      - run: echo ${GITHUB_REF#refs/heads/}
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      
        
      
        
      
