name: BMI

on:
  workflow_dispatch:
  push:
    branches:
      - workflows

env:
  BUILD_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  BUILD_TIMESTAMP: $(date -d "${{ github.event.head_commit.timestamp }}" +%Y-%m-%d\ %H:%M:%S)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      # Checkout and install prerequisites
      - name: Use Nodejs
        uses: actions/checkout@v3
        with:
          node-version: '16'
      - name: Artifactory 
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_EXPORT: ${{ secrets.JF_EXPORT }}
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Buildd
      - run: npm i
      - run: ls && pwd
      - run: tar -cvf build.tar.gz *
      - run: ls && pwd
      #SonarQube scan
#       - name: SonarQube Scan
#         uses: sonarsource/sonarqube-scan-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
      #Upload Artifactss
#       - run: jfrog --version
#       - run: jfrog config show
#       - run: jfrog rt upload --url=${{ secrets.JF_URL }} --user=admin --password=${{ secrets.JF_PASS }} "build.tar.gz" ga/${{github.run_number}}/
      - run: echo $GITHUB_ACTOR
      - name: Send notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
          "text": "
          Build Triggered by: '$GITHUB_ACTOR'
          Job URL: '$BUILD_URL'
          Project Name: '$GITHUB_REPOSITORY'
          Job Name: '$GITHUB_WORKFLOW'
          Build Number: '${{github.run_number}}'
          Branch Name: '$GITHUB_REF'
          Build Started at: '${{ github.event.head_commit.timestamp }}'
          BUILD EVENT: '$GITHUB_EVENT_NAME'
          "
          }' ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        

      
        
      
