name: BMI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      # Checkout and install prerequisites
      - name: Use Nodejs
        uses: actions/checkout@v3

      - name: Get Pull number
        run: echo ${{ github.event.number }}    
      
        
      
        
      
