
name: Test Get Email from Github Username

on:
  pull_request:
  push:

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  
jobs:
  prJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - run: | 
            echo "Pull Request Number ${{ github.event.pull_request.number }}"
            echo $GITHUB_PR_NUMBER

  get_user_email:
    runs-on: ubuntu-latest
    name: A job to get a users email
    steps:
      - name: clone
        uses: actions/checkout@v3
        
      - name: get mail
        run: | 
             echo $GITHUB_EVENT_PATH
             cat /home/runner/work/_temp/_github_workflow/event.json
