name: BMI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Nodejs
        uses: actions/checkout@v3
        with:
          node-version: '16'
      - run: npm i
      - run: ls && pwd
      - run: tar -cvf * build.tar.gz
      - run: ls
      - name: Artifactory 
        uses: jfrog/setup-jfrog-cli@v1
      - run: jfrog --version
        
      
