name: Email Notification

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Build
         run: echo "Build....."
       - name: display user  
         run: |
              users
              echo ${GITHUB_SHA::7}
    outputs:
       status_build: ${{ job.status }}
         
  test:
    runs-on: ubuntu-latest
    steps:
       - name: Build
         run: echo "Test....."
       - name: display user  
         run: users
    outputs:
       status_test: ${{ job.status }}
         
  send_notification:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: jaydeepkaushik@outlook.com
          password: ${{ secrets.OUTLOOK_APP_PASSWORD }}
          subject: Build Completed - ${{ github.workflow }} | ${{ github.action_status }}
          to: jaideepkaushik12@gmail.com
          cc: sarulathavimal@outlook.com
          from: jaydeepkaushik@outlook.com
          body: |
            Hi team,
            
            Project Name: ${{ github.repository }}
            The build job outcome was: ${{needs.build.outputs.status_build}}
            The test job outcome was: ${{needs.test.outputs.status_test}}
            Workflow Status: ${{ github.action_status }}
            Build Triggered by: ${{ github.triggering_actor }}
            Job URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Job Name: ${{ github.workflow }}
            Build Number: ${{github.run_number}}
            Branch Name: ${{ github.ref_name }}
            Build Started at: ${{ github.event.head_commit.timestamp }}
            BUILD EVENT: ${{ github.event_name }}

            Thanks,
            RSDO Team
