name: Email Notification

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Build
         run: echo "Build....."
    outputs:
       status_build: ${{ job.status }}
         
  test:
    runs-on: ubuntu-latest
    steps:
       - name: Build
         run: echo "Test....."
    outputs:
       status_test: ${{ job.status }}
         
  send_notification:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: jaydeepkaushik@outlook.com
          password: ${{ secrets.OUTLOOK_APP_PASSWORD }}
          subject: GitHub Action Notification
          to: jaydeepkaushik@outlook.com
          from: jaydeepkaushik@outlook.com
          body: |
            The build job outcome was: ${{needs.build.outputs.status_build}}
            The test job outcome was: ${{needs.test.outputs.status_test}}
            Job Status: ${{ job.status }}
            Build Triggered by: ${{ GITHUB_ACTOR}}
            Job URL: ${{ BUILD_URL }}
            Project Name: ${{ GITHUB_REPOSITORY }}
            Job Name: ${{ GITHUB_WORKFLOW }}
            Build Number: ${{github.run_number}}
            Branch Name: ${{ GITHUB_REF }}
            Build Started at: ${{ github.event.head_commit.timestamp }}
            BUILD EVENT: ${{ GITHUB_EVENT_NAME }}
